"""Update variables name in tweet and user table

Revision ID: 4de7f025ba24
Revises: 8bb1fa47ff81
Create Date: 2024-12-30 10:39:01.847946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de7f025ba24'
down_revision: Union[str, None] = '8bb1fa47ff81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'urls')
    op.add_column('users', sa.Column('statuses_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'status_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'statuses_count')
    op.add_column('tweets', sa.Column('urls', sa.TEXT(), autoincrement=False, nullable=True, comment='URL'))
    # ### end Alembic commands ###
