"""Initial migration

Revision ID: 5a6e79de2a8c
Revises: 
Create Date: 2024-12-29 15:25:51.322087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6e79de2a8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名前'),
    sa.Column('screen_name', sa.String(length=255), nullable=False, comment='スクリーンネーム'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='URL'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='説明'),
    sa.Column('is_blue_verified', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('favourites_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('status_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='ユーザー'
    )
    op.create_table('tweets',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tweet_id', sa.Text(), nullable=False, comment='ツイートID'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='作成日時'),
    sa.Column('urls', sa.Text(), nullable=True, comment='URL'),
    sa.Column('text', sa.Text(), nullable=False, comment='テキスト'),
    sa.Column('is_quote_status', sa.Boolean(), nullable=False, comment='引用ツイート'),
    sa.Column('reply_count', sa.Text(), nullable=False, comment='リプライ数'),
    sa.Column('favorite_count', sa.Text(), nullable=False, comment='お気に入り数'),
    sa.Column('view_count', sa.Text(), nullable=False, comment='ビュー数'),
    sa.Column('retweet_count', sa.Text(), nullable=False, comment='リツイート数'),
    sa.Column('retweeted_tweet_id', sa.Text(), nullable=True, comment='リツイートツイートID'),
    sa.Column('hashtags', sa.Text(), nullable=True, comment='ハッシュタグ'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='ツイート'
    )
    op.create_index(op.f('ix_tweets_user_id'), 'tweets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweets_user_id'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_table('users')
    # ### end Alembic commands ###
