"""Update tweets

Revision ID: 72c4d27522c6
Revises: 4a7cfd23c798
Create Date: 2024-12-29 16:59:51.684757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c4d27522c6'
down_revision: Union[str, None] = '4a7cfd23c798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'hashtags',
               existing_type=sa.TEXT(),
               type_=sa.ARRAY(sa.String(length=2048)),
                postgresql_using="hashtags::character varying(2048)[]",
               comment=None,
               existing_comment='ハッシュタグ',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'hashtags',
               existing_type=sa.ARRAY(sa.String(length=2048)),
               type_=sa.TEXT(),
               comment='ハッシュタグ',
               existing_nullable=True)
    # ### end Alembic commands ###
