"""Update tweet table

Revision ID: 8bb1fa47ff81
Revises: 04357ff5f6d1
Create Date: 2024-12-29 22:19:10.032938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb1fa47ff81'
down_revision: Union[str, None] = '04357ff5f6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'reply_count',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_comment='リプライ数',
               existing_nullable=False,
               postgresql_using="reply_count::integer")
    op.alter_column('tweets', 'favorite_count',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_comment='お気に入り数',
               existing_nullable=False,
               postgresql_using="favorite_count::integer")
    op.alter_column('tweets', 'view_count',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_comment='ビュー数',
               existing_nullable=False,
               postgresql_using="view_count::integer")
    op.alter_column('tweets', 'retweet_count',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_comment='リツイート数',
               existing_nullable=False,
               postgresql_using="retweet_count::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tweets', 'retweet_count',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_comment='リツイート数',
               existing_nullable=False)
    op.alter_column('tweets', 'view_count',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_comment='ビュー数',
               existing_nullable=False)
    op.alter_column('tweets', 'favorite_count',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_comment='お気に入り数',
               existing_nullable=False)
    op.alter_column('tweets', 'reply_count',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_comment='リプライ数',
               existing_nullable=False)
    # ### end Alembic commands ###
