"""create table accounts and cookies for crawling

Revision ID: bb8a2e0fddeb
Revises: 4de7f025ba24
Create Date: 2024-12-30 14:10:30.438763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8a2e0fddeb'
down_revision: Union[str, None] = '4de7f025ba24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('is_in_use', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='accounts_email_key')
    )
    op.create_table('cookies',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('account_id', sa.BIGINT(), nullable=True),
    sa.Column('ct0', sa.Text(), nullable=True),
    sa.Column('auth_token', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='cookies_account_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookies')
    op.drop_table('accounts')
    # ### end Alembic commands ###
